# Site settings
title: AUSKF Nationals 2017

email: web@auskf-nationals.com

description: > # this means to ignore newlines until "baseurl:"
  Official website for the AUSKF National Championships 2017
  
baseurl: ""

url: "http://locahost:4000" # the base hostname & protocol for your site

markdown: kramdown
